CREATE TABLE IF NOT EXISTS `upgrade_record` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '国家',
  `content` TEXT COMMENT '升级内容',
  `update_time` DATETIME DEFAULT NULL COMMENT '更新时间(北京)',
  `update_time_out` DATETIME DEFAULT NULL COMMENT '更新时间(当地)',
  `updater` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '研发人员',
  `tester` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '测试人员',
  `type` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '类型：新功能/新游戏/bug修复/功能优化',
  `platform` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '平台：Android/IOS/前端/后端/前后端/数据库',
  `impact` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '影响范围',
  `is_review` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已复盘 0-否 1-是',
  `review_conclusion` TEXT COMMENT '复盘结论(HTML)',
  `review_person` VARCHAR(255) DEFAULT '' COMMENT '复盘人员',
  `remark` TEXT COMMENT '备注',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_country` (`country`),
  INDEX `idx_update_time` (`update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='升级记录表';
